//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;facets&gt;
        ///    &lt;facet&gt;
        ///      &lt;name&gt;IComponent_1&lt;/name&gt;
        ///      &lt;interfaceName&gt;IDL:scs/core/IComponent:1.0&lt;/interfaceName&gt;
        ///      &lt;facetImpl assembly=&quot;Scs&quot;&gt;Scs.Core.Servant.IComponentServant&lt;/facetImpl&gt;
        ///    &lt;/facet&gt;
        ///    &lt;facet&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component1 {
            get {
                return ResourceManager.GetString("Component1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test7&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;context&gt;
        ///    &lt;type assembly=&quot;Test&quot;&gt;Test.Mock.InvalidClass&lt;/type&gt;
        ///  &lt;/context&gt;  
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component10 {
            get {
                return ResourceManager.GetString("Component10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;facets&gt;
        ///    &lt;facet&gt;
        ///      &lt;name&gt;IComponent_1&lt;/name&gt;
        ///      &lt;interfaceName&gt;IDL:scs/core/IComponent:1.0&lt;/interfaceName&gt;
        ///      &lt;facetImpl assembly=&quot;Invalid.Assambly&quot;&gt;Scs.Core.Servant.IComponentServant&lt;/facetImpl&gt;
        ///    &lt;/facet&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component2 {
            get {
                return ResourceManager.GetString("Component2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;facets&gt;
        ///    &lt;facet&gt;
        ///      &lt;name&gt;IComponent_1&lt;/name&gt;
        ///      &lt;interfaceName&gt;IDL:scs/core/IComponent:1.0&lt;/interfaceName&gt;
        ///      &lt;facetImpl assembly=&quot;Scs&quot;&gt;Scs.Core.Servant.InvalidClass&lt;/facetImpl&gt;
        ///    &lt;/facet&gt;
        ///  &lt;/facets&gt;
        ///&lt;/scs:co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component3 {
            get {
                return ResourceManager.GetString("Component3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;facets&gt;
        ///    &lt;facet&gt;
        ///      &lt;name&gt;IComponent_1&lt;/name&gt;
        ///      &lt;interfaceName&gt;IDL:scs/core/IComponent:1.0&lt;/interfaceName&gt;
        ///      &lt;facetImpl&gt;Scs.Core.Servant.IComponentServant&lt;/facetImpl&gt;
        ///    &lt;/facet&gt;
        ///  &lt;/facets&gt;
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component4 {
            get {
                return ResourceManager.GetString("Component4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;receptacles&gt;
        ///    &lt;receptacle&gt;
        ///      &lt;name&gt;Receptacle1&lt;/name&gt;
        ///      &lt;interfaceName&gt;IDL:scs/core/IMetaInterface:1.0&lt;/interfaceName&gt;
        ///      &lt;isMultiplex&gt;false&lt;/isMultiplex&gt;
        ///    &lt;/receptacle&gt;
        ///    &lt;receptacle&gt;
        ///      &lt;name&gt;Receptac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component5 {
            get {
                return ResourceManager.GetString("Component5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test1&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component6 {
            get {
                return ResourceManager.GetString("Component6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test7&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;context&gt;
        ///    &lt;type assembly=&quot;Test&quot;&gt;Test.Mock.MockComponentContext&lt;/type&gt;
        ///  &lt;/context&gt;  
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component7 {
            get {
                return ResourceManager.GetString("Component7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test8&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;context&gt;
        ///    &lt;type assembly=&quot;Test&quot;&gt;Test.Mock.MockComponentContext2&lt;/type&gt;
        ///  &lt;/context&gt;  
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component8 {
            get {
                return ResourceManager.GetString("Component8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;scs:component xmlns:scs=&quot;tecgraf.scs.core&quot;
        ///           xmlns:xi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;id&gt;
        ///    &lt;name&gt;Test9&lt;/name&gt;
        ///    &lt;version&gt;1.0.0&lt;/version&gt;
        ///    &lt;platformSpec&gt;.Net FrameWork 3.5&lt;/platformSpec&gt;
        ///  &lt;/id&gt;
        ///  &lt;context&gt;
        ///    &lt;type&gt;Test.Mock.MockComponentContext&lt;/type&gt;
        ///  &lt;/context&gt;  
        ///&lt;/scs:component&gt;.
        /// </summary>
        internal static string Component9 {
            get {
                return ResourceManager.GetString("Component9", resourceCulture);
            }
        }
    }
}
